import { StyleSheet } from 'react-native';
import * as Colors from './Colors';

const componentStyles = StyleSheet.create({
  cardUnitView: {
    flex: 1,
    backgroundColor: Colors.baseBackgroundPrimaryColor,
    alignItems: 'stretch',
    borderRadius: 10,
    marginRight: 5,
    marginTop: 9,
    marginBottom: 3,
    marginLeft: 5,
    shadowColor: Colors.defaultShadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardUnitColoredStrip: {
    flex: 0.25,
    marginLeft: 12,
    marginRight: 12,
    backgroundColor: Colors.basePrimaryColor,
    fontSize: 2,
    borderRadius: 20,
  },
  cardUnitImage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.baseBackgroundSecondaryColor,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 15,
    marginBottom: 10,
    height: 180,
    borderRadius: 10,
  },
  cardUnitDotsIcon: {
    flex: 0.10,
    alignSelf: 'center',
    marginLeft: 15,
  },
  boldTitle: {
    flex: 2,
    fontWeight: 'bold',
    fontSize: 15,
    marginLeft: 10,
  },
  ts: {
    flex: 1,
    marginLeft: 10,
    marginBottom: 15,
  },
  source: {
    flex: 1,
    color: Colors.basePrimaryColor,
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  cardUnitViewHorz: {
    flex: 1,
    backgroundColor: Colors.baseBackgroundPrimaryColor,
    alignItems: 'stretch',
    borderRadius: 10,
    marginRight: 5,
    marginTop: 9,
    marginBottom: 3,
    marginLeft: 5,
    shadowColor: Colors.defaultShadowColor,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    height: 200,
    width: 200,
  },
  cardUnitColoredStripHorz: {
    flex: 0.05,
    marginLeft: 12,
    marginRight: 12,
    backgroundColor: Colors.basePrimaryColor,
    fontSize: 2,
    borderRadius: 10,
  },
  cardUnitImageHorz: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.baseBackgroundSecondaryColor,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 15,
    marginBottom: 10,
    borderRadius: 10,
  },
});

export default componentStyles;